format = """
$username\
$directory\
$git_branch\
$git_status\
$fill\
$python\
$nodejs\
$cmd_duration\
$line_break\
$character\
"""

[fill]
symbol = " "

[python]
symbol = " "

[git_branch]
symbol = " "

[character]
format = "󰧣 "

[username]
style_user = 'blue bold'
style_root = 'black bold'
format = '[$user]($style) '
disabled = false
show_always = true
aliases = { "corpuser034g" = "matchati" }
