format = """
$username\
$directory\
$git_branch\
$git_status\
$fill\
$all\
$cmd_duration\
$line_break\
$character\
"""

[fill]
symbol = " "

[python]
symbol = " "

[git_branch]
symbol = " "

[character]
format = " "

[username]
style_user = 'blue bold'
style_root = 'black bold'
format = '󰣇 [$user]($style) '
disabled = false
show_always = true
aliases = { "corpuser034g" = "matchati" }

[git_status]
format = "[[$conflicted](yellow)[$untracked](218)[$modified$renamed](255)[$staged](green)[$deleted](red)($ahead_behind$stashed)]($style)"
conflicted = " $count "
untracked = " $count "
modified = " $count "
deleted = " $count "
staged = " $count "
renamed = " $count "
stashed = " $count "
style = "cyan"

[php]
symbol = " "

[bun]
symbol = " "
style = "yellow"
