"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
# A minimal left prompt
format = """$directory$character"""
# move the rest of the prompt to the right
right_format = """$all $cmd_duration"""

[character]
success_symbol = '[➜](bold fg:blue bg:base)[](bold base)'
error_symbol = '[✖](bold fg:red bg:base)[](bold base)'

[directory]
style = 'bold fg:text bg:base'
format = '[](bold base)[$path ]($style)[$read_only]($read_only_style)'
read_only_style = 'bold fg:red bg:mantle'

[git_branch]
format='[](bold base)[$symbol$branch(:$remote_branch) ](bold bg:base fg:text)[](bold base)'
style='bold bright fg:white bg:base'
symbol=" "

[git_status]
format = "[[$conflicted](yellow)[$untracked](blue)[$modified$renamed](yellow)[$staged](green)[$deleted](red)($ahead_behind$stashed)]($style)"
conflicted = " $count "
untracked = " $count "
modified = " $count "
deleted = " $count "
staged = " $count "
renamed = " $count "
stashed = " $count "
style = "cyan"

