"$schema" = 'https://starship.rs/config-schema.json'

format = """
$shell \
$directory\
$git_branch\
$fill\
$cmd_duration\
$all\
$character\
"""

add_newline = false

[character]
success_symbol = '[](bold green) [](bold yellow) [ ](bold green)'
error_symbol = '[ ✗  ](bold red) '

[cmd_duration]
min_time = 500
format = 'took [$duration](bold yellow) '

[shell]
fish_indicator = '󰈺 '
zsh_indicator = ''
powershell_indicator = '_'
unknown_indicator = '_'
style = 'cyan bold'
disabled = false

[username]
style_user = 'white bold'
style_root = 'black bold'
format = '[$user]($style) '
disabled = false
show_always = true
aliases = { "corpuser034g" = "matchati" }
