[main]
shell=/usr/bin/fish
font=SauceCodePro Nerd Font:size=22:weight=semibold
#line-height=36px
pad=16x12

[colors-dark]
background=0d1117
foreground=c9d7e8
regular0=0d1117
regular1=f0abfc
regular2=93c5fd
regular3=d19a66
regular4=7aa2f7
regular5=bb9af7
regular6=60a5fa
regular7=c9d7e8
bright0=6b7f99
bright1=f5d0fe
bright2=93c5fd
bright3=fff1c6
bright4=9cc9ff
bright5=f0abfc
bright6=7dd3fc
bright7=e6f0ff

alpha=0.8
