vim.g.mapleader = " "
vim.o.wrap = false
vim.o.backup = false
vim.o.expandtab = true
vim.o.hlsearch = false
vim.o.incsearch = true
vim.o.number = true
vim.o.scrolloff = 8
vim.o.shiftwidth = 4
vim.o.showmode = false
vim.o.signcolumn = "yes"
vim.o.smartindent = true
vim.o.softtabstop = 4
vim.o.swapfile = false
vim.o.tabstop = 4
vim.o.termguicolors = true
vim.o.updatetime = 50
vim.o.winborder = "rounded"
vim.o.mouse = ""
vim.opt.number = true
vim.opt.relativenumber = true
-- vim.o.autocomplete = true
-- vim.o.pumborder = 'rounded'
-- vim.o.pummaxwidth = 40
-- vim.o.completeopt = 'menu,menuone,noselect'
