vim.pack.add({
    "https://github.com/nvim-lua/plenary.nvim",
    "https://github.com/nvim-telescope/telescope.nvim",
    "https://github.com/neovim/nvim-lspconfig",
    "https://github.com/mason-org/mason.nvim",
    "https://github.com/mason-org/mason-lspconfig.nvim",
    "https://github.com/WhoIsSethDaniel/mason-tool-installer.nvim",
    "https://github.com/stevearc/conform.nvim",
    "https://github.com/lewis6991/gitsigns.nvim",
    "https://github.com/nvim-tree/nvim-tree.lua",
    "https://github.com/rachartier/tiny-inline-diagnostic.nvim",
    "https://github.com/hrsh7th/cmp-nvim-lsp",
    "https://github.com/hrsh7th/cmp-buffer",
    "https://github.com/hrsh7th/cmp-path",
    "https://github.com/hrsh7th/cmp-cmdline",
    "https://github.com/hrsh7th/nvim-cmp",
    "https://github.com/github/copilot.vim",
    "https://github.com/nvim-tree/nvim-web-devicons",
    "https://github.com/yioneko/nvim-vtsls",
    "https://github.com/nvim-lualine/lualine.nvim",
    "https://github.com/projekt0n/github-nvim-theme",
    "https://github.com/kdheepak/lazygit.nvim",
    "https://github.com/MeanderingProgrammer/render-markdown.nvim"
})

require("plugins.telescope")
require("plugins.conform")
require("plugins.gitsigns")
require("plugins.nvim-tree")
require("plugins.tiny-inline-diagnostic")
require("plugins.cmp")
require("plugins.copilot")
require("plugins.vtsls")
require("plugins.lualine")
require("plugins.github-theme")
require("plugins.render-markdown")
require("plugins.devicons")
